### ISSUE TITLE
OutOfRangeError  PaddingFIFOQueue 

### ISSUE THREAD

**Issue by Jnyle** [yangxue0827/R-DFPN_FPN_Tensorflow#21]
Traceback (most recent call last):
  File "train.py", line 298, in <module>
    train()
  File "train.py", line 259, in train
    fast_rcnn_total_loss, total_loss, train_op])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

Caused by op u'get_batch/batch', defined at:
  File "train.py", line 298, in <module>
    train()
  File "train.py", line 36, in train
    is_training=True)
  File "../data/io/read_tfrecord.py", line 85, in next_batch
    dynamic_pad=True)
hello, my question is as follows:

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

did anyone met the same problem?

**Comment by houyk1** [comment]
I met the same problem. Have you fix it ?

**Comment by fall-love** [comment]
@Jnyle I met the same problem. Have you fix it ? thank you!
