### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_rbbox_overlaps)

### ISSUE THREAD

**Issue by JavisPeng** [yangxue0827/R-DFPN_FPN_Tensorflow#7]
When I running python train.py，I encountered  this error message:
```
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from libs.rpn import build_rpn
  File "../libs/rpn/build_rpn.py", line 10, in <module>
    from libs.box_utils import iou_rotate
  File "../libs/box_utils/iou_rotate.py", line 10, in <module>
    from libs.box_utils.rbbox_overlaps import rbbx_overlaps
ImportError: dynamic module does not define module export function (PyInit_rbbox_overlaps)
```
Need I compile this cpp file again ?

env: centos7 +tensorflow1.8+cuda8.0+python3

**Comment by JavisPeng** [comment]
You can resolve this problem  with python2.7
